#!/bin/bash

echo "=== PostgreSQL Authentication Fix ==="
echo ""
echo "Option 1: Set password for postgres user"
echo "Run this command:"
echo "  sudo -u postgres psql -c \"ALTER USER postgres WITH PASSWORD 'postgres';\""
echo ""
echo "Option 2: Create a new user (recommended)"
echo "Run these commands:"
echo "  sudo -u postgres psql << EOF"
echo "  CREATE USER rental_user WITH PASSWORD 'rental_pass123';"
echo "  ALTER USER rental_user CREATEDB;"
echo "  GRANT ALL PRIVILEGES ON DATABASE rental_marketplace TO rental_user;"
echo "  EOF"
echo ""
echo "Then update your .env file:"
echo "  DATABASE_URL=\"postgresql://rental_user:rental_pass123@localhost:5432/rental_marketplace?schema=public\""
echo ""
echo "Option 3: Use peer authentication (no password needed)"
echo "Update your .env file to:"
echo "  DATABASE_URL=\"postgresql://postgres@localhost:5432/rental_marketplace?schema=public\""
echo ""

